server:
  port: 8888
spring:
  datasource:
    name: mysql_db
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://cdb-dzuvsk24.cd.tencentcdb.com:10075/intelligent_park_lot?useSSL=FALSE&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: yun@2020
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 2
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  profiles:
    active: dev

##mybaties\u914D\u7F6E
mybatis:
  mapper-locations: classpath*:mybaits/**/*Mapper.xml
  mapperLocations: classpath*:mybaits/**/*Mapper.xml
  config-location: classpath:mybaits/mybatis-config.xml
  configLocation: classpath:mybaits/mybaits-config.xml

##\u5206\u9875\u63D2\u4EF6\u914D\u7F6E
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
